### ISSUE TITLE
[Feature Request] 希望能添加 Snap 打包格式，以及提交到 Snap Store

### ISSUE THREAD

**Issue by twang2218** [Icalingua/Icalingua#241]
**Is your feature request related to a problem? Please describe.**

现在打包格式多种多样，非常感谢。不过如果能够提供 Snap 的打包格式，将会在 Ubuntu 及其衍生系统的桌面使用中会非常的方便。

当前如果想在 Ubuntu 中使用 Icalingua，需要来到 Github 页面手动下载 deb 或者 AppImage 来安装使用。如果想做到包管理以及版本控制，在 Ubuntu 上一般是两种方案，一种是自己做源，比如 PPA，但是需要维护对应于多个 Ubuntu 版本，还需要考虑依赖问题，相对工作量比较大；另一个办法是使用 Snap Store 发行，这样没有依赖问题，而且由于沙箱技术，安全性也会大大提高，另外也对推广 Ubuntu Linux 桌面有所帮助，因为进入 Snap Store 后，各个版本的 Ubuntu 都可以通过图形界面的形式在应用商店中，寻找并安装 Icalingua 软件。

对于可行性，一方面，`electron-builder` 中支持 `snap` 作为 `target`，所以一般 Electron 的应用问题不大；另外，我本地使用 `deb` 包打包 `snap` 进行尝试，基本操作问题不大，感觉是可行的。

这是我当前的 `snapcraft.yaml` 可以用做参考。

```yaml
name: icalingua
base: core18
version: '2.2.3'
summary: QQ (Unofficial Electron implementation)
description: |
  基于Electron打造的前端通讯框架，可以通过实现的后端在 Linux 平台下使用 QQ。

# grade: stable
grade: devel
confinement: strict
architectures:
  - build-on: amd64

parts:
  icalingua:
    plugin: dump
    source: https://github.com/Clansty/Icalingua/releases/download/v2.2.3/icalingua_2.2.3_amd64.deb
    # source: ./icalingua_2.2.3_amd64.deb
    source-type: deb
    stage-packages:
      # from deb depends
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libxss1
      - libxtst6
      - xdg-utils
      - libatspi2.0-0
      - libuuid1
      - libappindicator3-1
      - libsecret-1-0
      # from build warning
      - libasound2
      - libdrm2
      - libgbm1
      - libxshmfence1
      # TLS
      - ca-certificates
    override-pull: |
      snapcraftctl pull
      # Fix the executable's location
      sed -i -e 's|Exec=/opt/Icalingua/icalingua %U|Exec=icalingua %U|g' usr/share/applications/icalingua.desktop
      # Point icon to the correct location
      sed -i -e 's|Icon=icalingua|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/icalingua.png|g' usr/share/applications/icalingua.desktop

apps:
  icalingua:
    command: desktop-launch $SNAP/opt/Icalingua/icalingua --no-sandbox
    desktop: usr/share/applications/icalingua.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR
    extensions:
      - gnome-3-34
    plugs:
# desktop
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
# # electron
      - browser-support
      - gsettings
      - home
      - network
# audio
      - alsa
      - jack1
      - pulseaudio
      - audio-playback
      - audio-record
# # others
#       - avahi-observe
      - screen-inhibit-control
#       - upower-observe
      - bluez
# # qq
#       - hardware-observe
#     slots:
#       - mpris

```
